title: Prometheus
baseURL: https://prometheus-staging.netlify.com/
pygmentsCodeFences: true
pygmentsUseClasses: true

params:
  author: Prometheus
  description: |
    An open-source monitoring system with a dimensional data model, flexible query language, efficient time series database and modern alerting approach.
  keywords:
  - prometheus
  - monitoring
  - monitoring system
  - time series
  - time series database
  - alerting
  - metrics
  - telemetry
  announcement: |
    Join us at PromCon in Munich on August 9 & 10, 2018  —  [CfP & tickets](https://promcon.io/2018-munich/)
  hero:
    title: From metrics to insight
    subtitle: Power your metrics and alerting with the leading open source monitoring solution
  quote:
    text: Even though Borgmon remains internal to Google, the idea of treating time-series data as a data source for generating alerts is now accessible to everyone through those open source tools like Prometheus [...]
    source: |
      [**Site Reliability Engineering**: How Google Runs Production Systems](http://shop.oreilly.com/product/0636920041528.do) — (O'Reilly Media)
  logos:
    navbar: prometheus-logo-grey.svg
  opensource:
    message: |
      Prometheus is 100% open source and community-driven.
      
      All components are available under the [Apache 2 License](http://www.apache.org/licenses/LICENSE-2.0) on GitHub.
  users:
  - name: Argus
    url: http://argus-sec.com/
  - name: Boxever
    url: http://www.boxever.com
  - name: Branch
    url: http://www.branch.io
  - name: cesanta
    url: https://www.cesanta.com
  - name: CoreOS
    url: https://www.coreos.com
  - name: crononauta
    url: http://www.crononauta.com
  - name: digitalocean
    url: https://www.digitalocean.com
  - name: Docker
    url: https://www.docker.com
  - name: Ericsson
    url: https://www.ericsson.com
  - name: Eurotech
    url: https://www.eurotech.com
  - name: Fosdem
    url: https://www.fosdem.org
  - name: FreshTracks
    url: https://freshtracks.io
  - name: giantswarm
    url: https://giantswarm.io
  - name: Improbable
    url: http://improbable.io
  - name: Jodel
    url: https://www.jodel-app.com
  - name: JustWatch
    url: https://www.justwatch.com
  - name: Kumina
    url: https://www.kumina.nl
  - name: latencyat
    url: https://latency.at
  - name: Loodse
    url: https://loodse.com
  - name: MavenSecurities
    url: http://www.mavensecurities.com/
  - name: Outbrain
    url: http://www.outbrain.com
  - name: Percona
    url: https://www.percona.com
  - name: pingcap
    url: https://www.pingcap.com
  - name: Qaware
    url: https://www.qaware.de
  - name: quobyte
    url: http://www.quobyte.com
  - name: RobustPerception
    url: https://www.robustperception.io
  - name: ShowMax
    url: http://www.showmax.com
  - name: shuttlecloud
    url: https://www.shuttlecloud.com
  - name: soundcloud
    url: https://www.soundcloud.com
  - name: Spacenet
    url: https://www.space.net
  - name: Sysdig
    url: https://www.sysdig.com
  - name: transloadit
    url: https://transloadit.com
  - name: WeLearn
    url: https://www.uda100.com
  - name: unosoft
    url: https://www.unosoft.hu
  - name: variomedia
    url: https://www.variomedia.de
  - name: weave
    url: https://www.weave.works
  
  features:
  - title: Dimensional data
    icon: flask
    text: Prometheus implements a highly dimensional data model. Time series are identified by a metric name and a set of key-value pairs.
  - title: Powerful queries
    icon: search
    text: A flexible query language allows slicing and dicing of collected time series data in order to generate ad-hoc graphs, tables, and alerts.
  - title: Great visualization
    icon: chart-line
    fa: true
    text: |
      Prometheus has multiple modes for visualizing data: a built-in expression browser, [Grafana](https://grafana.com/) integration, and a console template language.
  - title: Efficient storage
    icon: database
    text: Prometheus stores time series in memory and on local disk in an efficient custom format. Scaling is achieved by functional sharding and federation.
  - title: Simple operation
    icon: cogs
    text: Each server is independent for reliability, relying only on local storage. Written in Go, all binaries are statically linked and easy to deploy.
  - title: Precise alerting
    icon: exclamation-triangle
    text: Alerts are defined based on Prometheus's flexible query language and maintain dimenstional information. An Alertmanager handles notifications and silencing.
  - title: Many client libraries
    icon: code
    fa: true
    text: Client libraries allow for easy instrumentation of services. Over ten languages are supported already and custom libraries are easy to implement.
  - title: Many integrations
    icon: cloud-upload-alt
    text: |
      Existing exporters allow for bridging of third-party data into Prometheus. Examples: system statistics, as well as Docker, HAProxy, StatsD, and JMX metrics.
